openapi: 3.0.1
info:
  title: Doc-It!
  description: Converts a MarkDown text block to an MS-Word documents and returns the URL to the MS-Word document
  version: "v1"
servers:
  - url: https://mapit.roboguide.xyz/doc-it
paths:
  /convert:
    get:
      operationId: getConvert
      summary: Convert MarkDown text to a Word document
      parameters:
        - name: text
          in: query
          required: true
          schema:
            type: string
            description: The text block, formatted as markdown, to be converted to a Word document
      responses:
        "200":
          description: url to the converted MS-Word document
          content:
            text/plain:
              schema:
                type: string
  /document/{uuid}:
    get:
      operationId: getDocument
      summary: Download a converted Word document
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: The converted Word document
          content:
            application/vnd.openxmlformats-officedocument.wordprocessingml.document:
              schema:
                type: string
                format: binary
