FROM node:alpine

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

RUN npm install --save node-cache
RUN npm i --save-dev @types/node-cache
RUN npm install --save uuid
RUN npm i --save-dev @types/uuid
RUN npm install --save markdown-it
RUN npm i --save-dev @types/markdown-it
RUN npm install --save html-docx-js
RUN npm i --save-dev @types/html-docx-js

COPY . .

ENV PORT=3500

EXPOSE 3500

CMD ["npm", "run", "dev"]